//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Report {
    
    private ReportInvoice[] invoicesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
    public ReportInvoice[] Invoices {
        get {
            return this.invoicesField;
        }
        set {
            this.invoicesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReportInvoice {
    
    private string iNVIDField;
    
    private string bILLERIDField;
    
    private string bILLERNAME1Field;
    
    private string iNVOICEEIDField;
    
    private string iNVOICEENAME1Field;
    
    private string eBIDField;
    
    private string tIMESTAMPField;
    
    private string eS3USERField;
    
    private string eRRORField;
    
    private string eRRORCODEField;
    
    /// <remarks/>
    public string INVID {
        get {
            return this.iNVIDField;
        }
        set {
            this.iNVIDField = value;
        }
    }
    
    /// <remarks/>
    public string BILLERID {
        get {
            return this.bILLERIDField;
        }
        set {
            this.bILLERIDField = value;
        }
    }
    
    /// <remarks/>
    public string BILLERNAME1 {
        get {
            return this.bILLERNAME1Field;
        }
        set {
            this.bILLERNAME1Field = value;
        }
    }
    
    /// <remarks/>
    public string INVOICEEID {
        get {
            return this.iNVOICEEIDField;
        }
        set {
            this.iNVOICEEIDField = value;
        }
    }
    
    /// <remarks/>
    public string INVOICEENAME1 {
        get {
            return this.iNVOICEENAME1Field;
        }
        set {
            this.iNVOICEENAME1Field = value;
        }
    }
    
    /// <remarks/>
    public string EBID {
        get {
            return this.eBIDField;
        }
        set {
            this.eBIDField = value;
        }
    }
    
    /// <remarks/>
    public string TIMESTAMP {
        get {
            return this.tIMESTAMPField;
        }
        set {
            this.tIMESTAMPField = value;
        }
    }
    
    /// <remarks/>
    public string ES3USER {
        get {
            return this.eS3USERField;
        }
        set {
            this.eS3USERField = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField;
        }
        set {
            this.eRRORField = value;
        }
    }
    
    /// <remarks/>
    public string ERRORCODE {
        get {
            return this.eRRORCODEField;
        }
        set {
            this.eRRORCODEField = value;
        }
    }
}
